### PR TITLE
Ability for user to show interest to the opportunity

### PR DESCRIPTION
**Pull request by OlegSubik**
### Describe the background of your pull request

- request interest modal in the opportunity relation section (visible only for authenticated users)

- modal with necessary fields and validation

-  mutations for relation create

### CODE REVIEW

**Comment by atstojanov** [comment]
The `interest reason` text area is not limited to 380 symbols. The mutation throws an error when the the field is longer than 380 symbols.
When scrolling the data is going under the text area title and make it unreadable. (see the image)
image

**Review by atstojanov — CHANGES_REQUESTED** [review]
Check comments

**Review by techsmyth — CHANGES_REQUESTED** [review]
Looks great! A few comments
- "Become a member" ==> "Interested in collaborating?"
- "Type of relation" ==> "Type of collaboration"
- Second level label is not then needed
- Options to be "Want to help build", "Interested in your solution", "Sharing knowlege / network", "Other"

**Review by atstojanov — APPROVED** [review]

**Review by techsmyth — APPROVED** [review]

**Comment by techsmyth** [comment]
A few other comments

**Pull request merged**
